N_CNN_LAYERS: 5 
N_RNN_LAYERS: 6 
RNN_DIM : 512
N_CLASS: 36 
N_FEATS: 128
STRIDE: 1
DROPOUT : 0.05
LEARNING_RATE: 0.00001
BATCH_SIZE: 56
EPOCHS: 256
OPTIMIZER: 'AdamW'
ACTIVATION: 'gelu'
LANGUAGE: 'POLISH'
CHECKPOINT_PATH: 'saved_models/common_voice_proper_dict.pt'